### ISSUE TITLE
[Bug] prettier 적용 안 되는 문제 해결, 타입 폴더 관련 import문 에러 해결, import문 순서 지정

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/gdsc-admin#16]
## ✨ 어떤 작업인가요?
현재 prettier가 작동하지 않는 문제, 타입 폴더 관련 import문에서 발생하는 에러가 있습니다.
이 에러들을 해결합니다.
또, import문 순서를 지정해주도록 설정 정보를 적용합니다.

## ☑ TODO
- [x] prettier 적용 안 되는 문제 해결
- [x] 타입 폴더 관련 import문 에러 해결
- [x] import문 순서 지정해주도록 설정
