### ISSUE TITLE
[Refactor] Header 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/gdsc-admin#74]
## ✨ 어떤 작업인가요?
현재는 전체 멤버 관리 페이지 기준 searchText, searchType을 지역 상태로 사용하고 있습니다.
그래서 Header 컴포넌트 자체에서는 이를 사용하지 않고 HeaderLeftCol, HeaderRightCol 컴포넌트에서만 사용합니다.
지역 상태를 사용하고 props drilling을 발생시키는 것보다 context api나 전역 상태로 관리해보려고 합니다.
다만, context api를 사용하기에는 여러 컴포넌트에서 해당 상태를 사용하고 있어 리렌더링 문제가 발생할 것 같습니다.
따라서, 전역 상태로 관리해보려고 합니다.

현재 selectedMember 관련 로직도 지역 상태로 관리 중인데, props drilling이 발생하기 때문에 변경이 필요합니다.
다만 이를 구독한 컴포넌트들이 많지 않고, 여러 컴포넌트에서 다른 값들을 가져다 써야 하기 때문에 컨텍스트 api로 변경합니다.

또한 HeaderLeftCol 로직이 상당히 복잡한데, 최대한 공통 로직을 빼고, 복잡한 if문을 object mapping 방식으로 리팩토링합니다.

### TO-BE
searchText, searchType를 전역 상태로 변경
HeaderLeftCol 관련 복잡한 로직들 리팩토링 (if문 로직 최대한 추상화, object mapping으로 변경)
selectedMember 관련 로직 컨텍스트 api로 변경

## ☑ TODO
- [x] searchText, searchType를 전역 상태로 변경
- [x] HeaderLeftCol 관련 복잡한 로직들 리팩토링 (if문 로직 최대한 추상화, object mapping으로 변경)
- [x] selectedMember 관련 로직 컨텍스트 api로 변경
