### ISSUE TITLE
[Refactor] 멤버 승인 모달 리팩토링

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/gdsc-admin#84]
## ✨ 어떤 작업인가요?
멤버 승인 모달 코드를 리팩토링합니다.

## ☑ TODO
- [x] 명령형 코드를 함수형 프로그래밍으로 변경
- [x] 불필요한 긴 코드 리팩토링
- [x] 불필요한 삼항 연산자 없애기
